kind: Deployment
apiVersion: apps/v1
metadata:
  name: content-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-provider
  template:
    metadata:
      labels:
        app: content-provider
    spec:
      containers:
        - name: content-provider
          image: czarek7777/content-provider:0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: content-provider
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: content-provider
